### ISSUE TITLE
Feedback needed: Should the dark mode class be applied to the <html> element rather than the DOM's body?

### ISSUE THREAD

**Issue by halfmoonui** [halfmoonui/halfmoon#37]
This is something I have been wondering for some time. Should the `.dark-mode` class be applied to the `<html>` element instead of the `<body>`? The main benefit of this is that global variables can be scoped depending on the mode. For example: 

```css
:root {
  --primary-color: darkblue;
}
.dark-mode {
  --primary-color: dodgerblue;
}
.btn-primary {
  background-color: var(--primary-color);
}
```
This way, colors can have different values based on the mode being used. This could be a way of solving the problem I brought up in https://github.com/halfmoonui/halfmoon/issues/27#issuecomment-678308820, and also just give more control.

Anyway, I would appreciate any comments or feedback on this issue: why you are **for** or **against** this possible change.
