### ISSUE TITLE
input switch transition

### ISSUE THREAD

**Issue by ThaUnknown** [halfmoonui/halfmoon#42]
would be nice to add a simple transition to the checkmark switch like so:
```css
.custom-switch input[type=checkbox]:checked~label:after,
.custom-switch input[type=checkbox]~label:after{
    transition: left .2s ease
}
``` 
it's really simple and makes it feel a LOT better
