### ISSUE TITLE
sidebar animation improvement

### ISSUE THREAD

**Issue by ThaUnknown** [halfmoonui/halfmoon#43]
the sidebar animation looks poor because of how much its moved offscreen, this can easily be fixed with:
```css
.page-wrapper.with-sidebar[data-sidebar-hidden]>.sidebar {
    left: calc(-1 *var(--sidebar-width));
}
```
